services:
  db:
    image: postgres:16
    container_name: limiarcontrol-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: limiarcontrol
    ports:
      - "5432:5432"
    volumes:
      - limiarcontrol_db:/var/lib/postgresql/data

volumes:
  limiarcontrol_db:
